// Simulated listing inventory. In production this would be fed by licensed
// listing APIs (MLS/Zillow partner feeds, Peerspace, Giggster) and the floor
// plans would come from a photogrammetry pipeline (Matterport, NeRF/Gaussian
// splatting over listing photos). Floor plan units are meters.

export const TYPES = {
  studio:     { label: 'Studio',     icon: '🎬', color: '#7fb4ff' },
  loft:       { label: 'Loft',       icon: '🪟', color: '#e8b45a' },
  warehouse:  { label: 'Warehouse',  icon: '🏭', color: '#d97b4f' },
  house:      { label: 'House',      icon: '🏡', color: '#7aa874' },
  rooftop:    { label: 'Rooftop',    icon: '🌆', color: '#c77fff' },
  storefront: { label: 'Storefront', icon: '🍸', color: '#e85a7f' },
  gallery:    { label: 'Gallery',    icon: '🖼️', color: '#9aa7b8' },
  estate:     { label: 'Estate',     icon: '🏛️', color: '#d4b96a' },
};

export const LIGHT_LABELS = {
  abundant: 'Abundant natural light',
  moderate: 'Moderate natural light',
  controlled: 'Blackout / controlled',
};

export const CENTERS = [
  { name: 'Downtown LA',  lat: 34.0407, lng: -118.2468 },
  { name: 'Hollywood',    lat: 34.0928, lng: -118.3287 },
  { name: 'Venice Beach', lat: 33.9850, lng: -118.4695 },
  { name: 'Culver City',  lat: 34.0219, lng: -118.3965 },
  { name: 'Pasadena',     lat: 34.1478, lng: -118.1445 },
  { name: 'Long Beach',   lat: 33.7701, lng: -118.1937 },
];

export const LOCATIONS = [
  {
    id: 'arts-district-loft',
    name: 'Arts District Daylight Loft',
    type: 'loft',
    neighborhood: 'Arts District, DTLA',
    address: '812 E 3rd St, Los Angeles, CA',
    lat: 34.0421, lng: -118.2357,
    sqft: 3200, ceilingFt: 14, rate: 250,
    light: 'abundant',
    tags: ['exposed brick', 'skylights', 'freight elevator', 'north light'],
    desc: 'Corner loft with a wall of steel-frame windows, raw brick, and two skylights over the main floor — a natural-light workhorse for editorial and lookbook shoots.',
    palette: { wall: '#b8a894', floor: '#8a6f52', accent: '#e8b45a' },
    floorplan: {
      rooms: [
        { name: 'Main Loft',   x: 0,  z: 0, w: 15, d: 12, h: 4.3, style: 'loft',    win: { n: 4, w: 3 }, sky: 2 },
        { name: 'Kitchenette', x: 15, z: 0, w: 5,  d: 6,  h: 3.2, style: 'kitchen', win: { n: 1, e: 1 } },
        { name: 'Green Room',  x: 15, z: 6, w: 5,  d: 6,  h: 3.2, style: 'lounge',  win: { e: 1, s: 1 } },
      ],
      doors: [
        { x: 15, z: 3, dir: 'v', width: 1.6 },
        { x: 15, z: 9, dir: 'v', width: 1.6 },
        { x: 17.5, z: 6, dir: 'h', width: 1.2 },
      ],
    },
  },
  {
    id: 'sunset-cyc-studio',
    name: 'Sunset Cyc Studio',
    type: 'studio',
    neighborhood: 'Hollywood',
    address: '1522 N Cahuenga Blvd, Los Angeles, CA',
    lat: 34.0977, lng: -118.3301,
    sqft: 4800, ceilingFt: 20, rate: 395,
    light: 'controlled',
    tags: ['white cyc', '400A power', 'blackout', 'client lounge'],
    desc: 'Full blackout stage with a 40-ft white cyc, dedicated control room, and makeup suite — built for commercial and music-video work.',
    palette: { wall: '#9aa1ad', floor: '#3d4148', accent: '#7fb4ff' },
    floorplan: {
      rooms: [
        { name: 'Stage A',      x: 0,  z: 0,   w: 18, d: 14,  h: 6,   style: 'studio' },
        { name: 'Control Room', x: 18, z: 0,   w: 6,  d: 5,   h: 3,   style: 'control', win: { e: 1 } },
        { name: 'Makeup',       x: 18, z: 5,   w: 6,  d: 4.5, h: 3,   style: 'makeup',  win: { e: 1 } },
        { name: 'Lounge',       x: 18, z: 9.5, w: 6,  d: 4.5, h: 3,   style: 'lounge',  win: { e: 1, s: 1 } },
      ],
      doors: [
        { x: 18, z: 2.5, dir: 'v', width: 1.6 },
        { x: 18, z: 7.2, dir: 'v', width: 1.4 },
        { x: 18, z: 11.7, dir: 'v', width: 1.4 },
        { x: 21, z: 5, dir: 'h', width: 1.2 },
        { x: 21, z: 9.5, dir: 'h', width: 1.2 },
      ],
    },
  },
  {
    id: 'venice-bungalow',
    name: 'Venice Craftsman Bungalow',
    type: 'house',
    neighborhood: 'Venice',
    address: '671 Palms Blvd, Venice, CA',
    lat: 33.9908, lng: -118.4661,
    sqft: 1750, ceilingFt: 10, rate: 180,
    light: 'abundant',
    tags: ['original wood', 'garden', 'morning light', 'quiet street'],
    desc: '1920s craftsman with warm original wood, soft coastal light, and a private garden — ideal for lifestyle, food, and intimate narrative scenes.',
    palette: { wall: '#d8cbb4', floor: '#9c7a54', accent: '#7aa874' },
    floorplan: {
      rooms: [
        { name: 'Living Room', x: 0, z: 0, w: 6, d: 5,   h: 2.9, style: 'living',  win: { n: 2, w: 1 } },
        { name: 'Kitchen',     x: 6, z: 0, w: 5, d: 5,   h: 2.9, style: 'kitchen', win: { n: 1, e: 1 } },
        { name: 'Bedroom',     x: 0, z: 5, w: 6, d: 4.5, h: 2.9, style: 'bed',     win: { w: 1, s: 2 } },
        { name: 'Studio Room', x: 6, z: 5, w: 5, d: 4.5, h: 2.9, style: 'office',  win: { s: 1, e: 1 } },
      ],
      doors: [
        { x: 6, z: 2.2, dir: 'v', width: 1.3 },
        { x: 2.8, z: 5, dir: 'h', width: 1.2 },
        { x: 8.6, z: 5, dir: 'h', width: 1.2 },
      ],
    },
  },
  {
    id: 'frogtown-warehouse',
    name: 'Frogtown Warehouse Stage',
    type: 'warehouse',
    neighborhood: 'Elysian Valley',
    address: '2910 Gilroy St, Los Angeles, CA',
    lat: 34.1091, lng: -118.2429,
    sqft: 9200, ceilingFt: 23, rate: 320,
    light: 'moderate',
    tags: ['drive-in door', 'skylights', 'raw concrete', 'grip trucks OK'],
    desc: 'Cavernous bow-truss warehouse with four skylights and a drive-in door — room for builds, car shoots, and large set pieces.',
    palette: { wall: '#8d8d94', floor: '#6e6a63', accent: '#d97b4f' },
    floorplan: {
      rooms: [
        { name: 'Main Floor', x: 0,  z: 0, w: 30, d: 24, h: 7,   style: 'warehouse', win: { n: 3 }, sky: 4 },
        { name: 'Office',     x: 30, z: 0, w: 8,  d: 6,  h: 3,   style: 'office',    win: { e: 2, n: 1 } },
        { name: 'Workshop',   x: 30, z: 6, w: 8,  d: 9,  h: 3.5, style: 'shop',      win: { e: 2 } },
      ],
      doors: [
        { x: 30, z: 3, dir: 'v', width: 1.8 },
        { x: 30, z: 10, dir: 'v', width: 2.4 },
        { x: 34, z: 6, dir: 'h', width: 1.4 },
      ],
    },
  },
  {
    id: 'silverlake-midcentury',
    name: 'Mid-Century Hillside House',
    type: 'house',
    neighborhood: 'Silver Lake',
    address: '2246 Moreno Dr, Los Angeles, CA',
    lat: 34.0932, lng: -118.2669,
    sqft: 2400, ceilingFt: 11, rate: 275,
    light: 'abundant',
    tags: ['walls of glass', 'canyon views', 'pool deck', 'terrazzo'],
    desc: 'Post-and-beam mid-century with glass walls and canyon light all day — a favorite for fashion, automotive stills, and interview setups.',
    palette: { wall: '#e2d6c2', floor: '#a3743f', accent: '#c96f4a' },
    floorplan: {
      rooms: [
        { name: 'Great Room',      x: 0, z: 0, w: 9, d: 7, h: 3.4, style: 'living',  win: { n: 3, w: 2 } },
        { name: 'Kitchen',         x: 9, z: 0, w: 5, d: 4, h: 3,   style: 'kitchen', win: { n: 1, e: 1 } },
        { name: 'Den',             x: 9, z: 4, w: 5, d: 3, h: 3,   style: 'lounge',  win: { e: 1 } },
        { name: 'Primary Bedroom', x: 0, z: 7, w: 6, d: 5, h: 3,   style: 'bed',     win: { s: 2, w: 1 } },
      ],
      doors: [
        { x: 9, z: 2, dir: 'v', width: 1.5 },
        { x: 9, z: 5.5, dir: 'v', width: 1.4 },
        { x: 3, z: 7, dir: 'h', width: 1.3 },
      ],
    },
  },
  {
    id: 'culver-rooftop',
    name: 'Culver Rooftop Terrace',
    type: 'rooftop',
    neighborhood: 'Culver City',
    address: '9300 Culver Blvd, Culver City, CA',
    lat: 34.0257, lng: -118.3852,
    sqft: 2000, ceilingFt: 0, rate: 200,
    light: 'abundant',
    tags: ['skyline views', 'golden hour', 'string lights', 'fire pit'],
    desc: 'Wraparound rooftop deck with a glass penthouse lounge, string lights, and unobstructed west-facing skyline — golden hour is the whole point.',
    palette: { wall: '#aab3bd', floor: '#8f8577', accent: '#e8b45a' },
    outdoor: true,
    floorplan: {
      rooms: [
        { name: 'Main Deck',        x: 0,  z: 0, w: 14, d: 9, h: 1.1, style: 'deck', open: true },
        { name: 'West Deck',        x: 14, z: 4, w: 6,  d: 5, h: 1.1, style: 'deck', open: true },
        { name: 'Penthouse Lounge', x: 14, z: 0, w: 6,  d: 4, h: 3,   style: 'lounge', win: { n: 2, e: 1 } },
      ],
      doors: [
        { x: 14, z: 2, dir: 'v', width: 1.6 },
        { x: 14, z: 6.5, dir: 'v', width: 5 },
        { x: 17, z: 4, dir: 'h', width: 1.4 },
      ],
    },
  },
  {
    id: 'pasadena-estate',
    name: 'Pasadena Estate & Gardens',
    type: 'estate',
    neighborhood: 'Pasadena',
    address: '1288 S Oakland Ave, Pasadena, CA',
    lat: 34.1497, lng: -118.1322,
    sqft: 6800, ceilingFt: 15, rate: 500,
    light: 'abundant',
    tags: ['ballroom', 'parquet', 'chandeliers', 'formal gardens'],
    desc: '1911 estate with a chandeliered ballroom, paneled library, and glass conservatory — period drama, weddings-editorial, and prestige-TV ready.',
    palette: { wall: '#e6ddcc', floor: '#b49664', accent: '#a3823c' },
    floorplan: {
      rooms: [
        { name: 'Ballroom',     x: 0,  z: 0, w: 12, d: 9, h: 4.6, style: 'ballroom',     win: { n: 4, w: 2 } },
        { name: 'Foyer',        x: 12, z: 0, w: 6,  d: 9, h: 4.6, style: 'foyer',        win: { n: 2 } },
        { name: 'Library',      x: 18, z: 0, w: 6,  d: 5, h: 3.4, style: 'library',      win: { n: 1, e: 1 } },
        { name: 'Dining Room',  x: 18, z: 5, w: 6,  d: 4, h: 3.4, style: 'dining',       win: { e: 1, s: 1 } },
        { name: 'Conservatory', x: 12, z: 9, w: 6,  d: 5, h: 3.6, style: 'conservatory', win: { s: 2, e: 2 }, sky: 2 },
      ],
      doors: [
        { x: 12, z: 4.5, dir: 'v', width: 2.2 },
        { x: 18, z: 2.5, dir: 'v', width: 1.5 },
        { x: 21, z: 5, dir: 'h', width: 1.3 },
        { x: 18, z: 7, dir: 'v', width: 1.4 },
        { x: 15, z: 9, dir: 'h', width: 1.8 },
      ],
    },
  },
  {
    id: 'santa-monica-studio',
    name: 'Santa Monica Photo Studio',
    type: 'studio',
    neighborhood: 'Santa Monica',
    address: '2929 Nebraska Ave, Santa Monica, CA',
    lat: 34.0246, lng: -118.4941,
    sqft: 2600, ceilingFt: 16, rate: 310,
    light: 'abundant',
    tags: ['cyc wall', 'ocean light', 'rolling blackout', 'client lounge'],
    desc: 'West-facing daylight studio with a hard cyc and rolling blackout — shoot soft ocean light all afternoon, then flip to strobes in minutes.',
    palette: { wall: '#eceff2', floor: '#cfd3d8', accent: '#5aa7e8' },
    floorplan: {
      rooms: [
        { name: 'Studio',        x: 0,  z: 0,   w: 14, d: 11,  h: 4.8, style: 'studio', win: { w: 3 }, sky: 1 },
        { name: 'Client Lounge', x: 14, z: 0,   w: 6,  d: 5.5, h: 3.2, style: 'lounge', win: { n: 1, e: 1 } },
        { name: 'Styling Suite', x: 14, z: 5.5, w: 6,  d: 5.5, h: 3.2, style: 'makeup', win: { e: 1, s: 1 } },
      ],
      doors: [
        { x: 14, z: 2.7, dir: 'v', width: 1.6 },
        { x: 14, z: 8.2, dir: 'v', width: 1.6 },
        { x: 17, z: 5.5, dir: 'h', width: 1.2 },
      ],
    },
  },
  {
    id: 'echo-park-bar',
    name: 'Echo Park Storefront Bar',
    type: 'storefront',
    neighborhood: 'Echo Park',
    address: '1642 W Sunset Blvd, Los Angeles, CA',
    lat: 34.0778, lng: -118.2607,
    sqft: 1900, ceilingFt: 12, rate: 220,
    light: 'moderate',
    tags: ['neon signage', 'vintage bar', 'checker floor', 'closed Mondays'],
    desc: 'Working neighborhood bar with original neon and a 30-ft mahogany counter — available for stills and night-interior scenes on dark days.',
    palette: { wall: '#6e3b3b', floor: '#31343a', accent: '#e85a7f' },
    floorplan: {
      rooms: [
        { name: 'Bar Room',    x: 0, z: 0, w: 12, d: 8, h: 3.6, style: 'bar',     win: { n: 3 } },
        { name: 'Back Lounge', x: 0, z: 8, w: 7,  d: 6, h: 3.2, style: 'lounge',  win: { w: 1 } },
        { name: 'Kitchen',     x: 7, z: 8, w: 5,  d: 6, h: 3.2, style: 'kitchen', win: { s: 1, e: 1 } },
      ],
      doors: [
        { x: 3.5, z: 8, dir: 'h', width: 1.6 },
        { x: 9, z: 8, dir: 'h', width: 1.4 },
        { x: 7, z: 11, dir: 'v', width: 1.2 },
      ],
    },
  },
  {
    id: 'long-beach-gallery',
    name: 'Long Beach Gallery White Box',
    type: 'gallery',
    neighborhood: 'East Village Arts District',
    address: '435 E Broadway, Long Beach, CA',
    lat: 33.7726, lng: -118.1935,
    sqft: 3000, ceilingFt: 14, rate: 260,
    light: 'moderate',
    tags: ['white walls', 'polished concrete', 'track lighting', 'street parking'],
    desc: 'Two connected white-box galleries under diffused skylights with polished concrete floors — a clean canvas for product, art, and set builds.',
    palette: { wall: '#f0f0f0', floor: '#c9c9c9', accent: '#e8b45a' },
    floorplan: {
      rooms: [
        { name: 'Gallery A',    x: 0,  z: 0, w: 12, d: 9, h: 4.2, style: 'gallery', win: { n: 1 }, sky: 3 },
        { name: 'Gallery B',    x: 12, z: 0, w: 8,  d: 9, h: 4.2, style: 'gallery', sky: 2 },
        { name: 'Project Room', x: 0,  z: 9, w: 6,  d: 5, h: 3.2, style: 'office',  win: { s: 1, w: 1 } },
      ],
      doors: [
        { x: 12, z: 4.5, dir: 'v', width: 2.6 },
        { x: 3, z: 9, dir: 'h', width: 1.8 },
      ],
    },
  },
  {
    id: 'burbank-stage-7',
    name: 'Burbank Sound Stage 7',
    type: 'studio',
    neighborhood: 'Burbank Media District',
    address: '2801 W Alameda Ave, Burbank, CA',
    lat: 34.1852, lng: -118.3253,
    sqft: 12000, ceilingFt: 30, rate: 600,
    light: 'controlled',
    tags: ['sound stage', '1200A power', 'grid at 28ft', 'drive-in door'],
    desc: 'Purpose-built sound stage with full grid, 1200A of power, and production offices down the wall — episodic and feature ready.',
    palette: { wall: '#6b7078', floor: '#41454c', accent: '#ffd166' },
    floorplan: {
      rooms: [
        { name: 'Stage',             x: 0,  z: 0,  w: 30, d: 26, h: 9, style: 'studio' },
        { name: 'Production Office', x: 30, z: 0,  w: 8,  d: 7,  h: 3, style: 'office', win: { e: 2 } },
        { name: 'Green Room',        x: 30, z: 7,  w: 8,  d: 6,  h: 3, style: 'lounge', win: { e: 1 } },
        { name: 'Hair & Makeup',     x: 30, z: 13, w: 8,  d: 6,  h: 3, style: 'makeup', win: { e: 1 } },
      ],
      doors: [
        { x: 30, z: 3.5, dir: 'v', width: 2 },
        { x: 30, z: 10, dir: 'v', width: 1.6 },
        { x: 30, z: 16, dir: 'v', width: 1.6 },
        { x: 34, z: 7, dir: 'h', width: 1.2 },
        { x: 34, z: 13, dir: 'h', width: 1.2 },
      ],
    },
  },
  {
    id: 'highland-park-house',
    name: 'Highland Park Vintage House',
    type: 'house',
    neighborhood: 'Highland Park',
    address: '5716 Aldama St, Los Angeles, CA',
    lat: 34.1155, lng: -118.1919,
    sqft: 1500, ceilingFt: 9, rate: 150,
    light: 'moderate',
    tags: ['original wood floors', 'clawfoot tub', 'garden', 'budget friendly'],
    desc: 'Untouched 1908 four-square with patinaed wood floors and a sun room — a budget-friendly period look that reads beautifully on camera.',
    palette: { wall: '#d9c8ae', floor: '#8f6b45', accent: '#7d9c6f' },
    floorplan: {
      rooms: [
        { name: 'Living Room', x: 0,   z: 0,   w: 5.5, d: 4.5, h: 2.8, style: 'living',       win: { n: 2, w: 1 } },
        { name: 'Kitchen',     x: 5.5, z: 0,   w: 4.5, d: 4.5, h: 2.8, style: 'kitchen',      win: { n: 1, e: 1 } },
        { name: 'Bedroom',     x: 0,   z: 4.5, w: 5.5, d: 4,   h: 2.8, style: 'bed',          win: { s: 1, w: 1 } },
        { name: 'Sun Room',    x: 5.5, z: 4.5, w: 4.5, d: 4,   h: 2.8, style: 'conservatory', win: { s: 2, e: 1 } },
      ],
      doors: [
        { x: 5.5, z: 2, dir: 'v', width: 1.2 },
        { x: 2.5, z: 4.5, dir: 'h', width: 1.1 },
        { x: 7.5, z: 4.5, dir: 'h', width: 1.2 },
      ],
    },
  },
];
